export const GRACE_PERIOD: number = 30;
export const CANCELLABLE_PERIOD_MINUTES: number = 5;
export const GRACE_PERIOD_EARLY_ENTERANCE_MINUTES: number = 15;
export const GRACE_PERIOD_TO_LEAVE_AFTER_SESSION_END_TIME: number = 10;
export const MAX_ALLOWED_HOURS_TO_EXTEND_SESSION: number = 8;
export const OCCUPANCY_CHECK_DELAY_AFTER_ENTRY = 10 * 60 * 1000;
export const MAX_RESERVATION_HOURS = 5




export const RESERVATION_CHECK_IF_IT_HAS_CONTINUE = 10;
//BILLING
export const REGULAR_RATE_PER_MINUTE = 0.5; // EGP per minute
export const PENALTY_RATE_PER_MINUTE = 1.0; // EGP per minute (Higher rate)
export const CONFLICT_FEE = 20.0; // EGP fixed fee for causing conflict
export const MINIMUM_CHARGE = 70.0; // EGP minimum charge for any session
export const NO_SHOW_PENALTY_AMOUNT = 100.0;
export const HOLDAMOUNT_WHILE_RESERVATIONS = 10000;




export const CANCELED_RESERVATION_EMITTER_MESSAGE = "CANCELED_RESERVATION";
export const SLOT_STATUS_CHANGED_MESSAGE = "SLOT_STATUS_CHANGED"
export const VERIFYING_PLATE_GATE_ENTRY = "VERIFYING_PLATE_GATE_ENTRY";
export const DECISION_GATE_ENTRY_EMIT = "DECISION_GATE_ENTRY_EMIT";
export const HANDLE_SLOT_ENTER_EMIT = "HANDLE_SLOT_ENTER_EMIT"
export const SESSION_SLOT_NOT_OCCUPIED_BEFORE_TOLERANCETIME = "SESSION_SLOT_NOT_OCCUPIED_BEFORE_TOLERANCETIME"
export const HANDLE_SLOT_HAS_BEEN_OVERTAKEN = "HANDLE_SLOT_HAS_BEEN_OVERTAKEN"
export const HANDLE_HAS_DONE_VIOLATION = "HANDLE_HAS_DONE_VIOLATION"
export const HANDLE_SLOT_EXIT_EMIT = "HANDLE_SLOT_EXIT_EMIT"
export const HANDLE_GATE_EXIT_EMIT = "HANDLE_GATE_EXIT_EMIT"
export const PAYMENT_FAILED_AND_BLACKLISTED = "PAYMENT_FAILED_AND_BLACKLISTED";
export const DEBT_CLEARED = "DEBT_CLEARED"
export const USER_DATA_UPDATED = "USER_DATA_UPDATED"